
- name: Deploy Windows Admin Center
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - set_fact:
      resourcegroup: "RG-WindowsAdminCenter2"
      vmname: "ls-wac2"
      tag_event: "MVPDagen2018"

  - name: Notify in Teams
    uri:
      url: https://outlook.office.com/webhook/aece0949-c7b2-48a5-9dc2-f4351e5dc925@8fec7cb8-30e7-4d8a-98ae-6e64853af4a3/IncomingWebhook/59a5ebb5dd7f4741bd0e9f515169f776/e64f54d5-1068-453c-9772-b1d403cce6fb
      method: POST
      body: "{% include 'ansible_alert.json' %}"
      body_format: json
      headers:
        Content-Type: "application/json"

  - name: Create PIP
    azure_rm_publicipaddress:
      auth_source: auto
      profile: default
      resource_group: "{{ resourcegroup }}"
      name: "{{ 'PIP-' + vmname }}"
      allocation_method: Static
      domain_name: "{{ vmname }}"
      tags:
        event: "{{ tag_event }}"

  - name: Create NIC
    azure_rm_networkinterface:
      auth_source: auto
      profile: default
      resource_group: "{{ resourcegroup }}"
      name: "{{ 'NIC-' + vmname }}"
      virtual_network_name: "/subscriptions/3cf46281-f639-44bc-a338-11697697bb2a/resourceGroups/LangskipNetwork/providers/Microsoft.Network/virtualNetworks/vNet-Langskip-WE"
      subnet_name: "Servers-Static"
      os_type: Windows
      open_ports:
       - 443
       - 3389
       - 5986
       - 6516
      ip_configurations:
        - name: ipconfig1
          public_ip_address_name: "{{ 'PIP-' + vmname }}"
          primary: True
      tags:
        event: "{{ tag_event }}"

  - name: Create virtual machine
    azure_rm_virtualmachine:
      auth_source: auto
      profile: default
      resource_group: "{{ resourcegroup }}"
      name: "{{ vmname }}"
      vm_size: "Standard_D2s_v3"
      admin_username: "localadmin"
      admin_password: "VeryStrongP@ssw0rd!"
      network_interface_names: "{{ 'NIC-' + vmname }}"
      managed_disk_type: "Premium_LRS"
      os_type: Windows
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: '2016-Datacenter'
        version: 'latest'
      tags:
        event: "{{ tag_event }}"

  - name: VM user assigned identity
    command: az vm identity assign -g "{{ resourcegroup }}" -n "{{ vmname }}" --identities "/subscriptions/3cf46281-f639-44bc-a338-11697697bb2a/resourcegroups/RG-WindowsAdminCenter/providers/Microsoft.ManagedIdentity/userAssignedIdentities/kvreader"

  - name: Create VM Extension
    azure_rm_virtualmachine_extension:
      auth_source: auto
      profile: default
      name: WACCustomScript
      resource_group: "{{ resourcegroup }}"
      virtual_machine_name: "{{ vmname }}"
      publisher: Microsoft.Compute
      virtual_machine_extension_type: CustomScriptExtension
      type_handler_version: 1.9
      settings: '{"fileUris": ["https://raw.githubusercontent.com/morgansimonsen/MVPDagen2018/master/wac/Install-WAC.ps1"],"commandToExecute": "powershell.exe -ExecutionPolicy Unrestricted -file Install-WAC.ps1"}'
      auto_upgrade_minor_version: true