
- name: Create Azure RGs
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:

  - name: Create Azure RG for WAC
    azure_rm_resourcegroup:
      name: RG-WindowsAdminCenter
      location: westeurope
      tags:
          event: MVPDagen2018