
- name: Deploy Windows Admin Center
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: Create PIP
    azure_rm_publicipaddress:
      auth_source: auto
      profile: default
      resource_group: "RG-WindowsAdminCenter"
      name: "PIP-ls-wac1"
      allocation_method: Static
      domain_name: ls-wac1
      tags:
        event: MVPDagen2018

  - name: Create NIC
    azure_rm_networkinterface:
      auth_source: auto
      profile: default
      resource_group: "RG-WindowsAdminCenter"
      name: "NIC-ls-wac1"
      virtual_network_name: "/subscriptions/3cf46281-f639-44bc-a338-11697697bb2a/resourceGroups/LangskipNetwork/providers/Microsoft.Network/virtualNetworks/vNet-Langskip-WE"
      subnet_name: "Servers-Static"
      os_type: Windows
      open_ports:
       - 3389
       - 5986
       - 6516
      ip_configurations:
        - name: ipconfig1
          public_ip_address_name: "PIP-ls-wac1"
          primary: True
      tags:
        event: MVPDagen2018

  - name: Create virtual machine
    azure_rm_virtualmachine:
      auth_source: auto
      profile: default
      resource_group: "RG-WindowsAdminCenter"
      name: "ls-wac1"
      vm_size: "Standard_D2s_v3"
      admin_username: "localadmin"
      admin_password: "VeryStrongP@ssw0rd!"
      network_interface_names: "NIC-ls-wac1"
      managed_disk_type: "Premium_LRS"
      os_type: Windows
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: '2016-Datacenter'
        version: 'latest'
      tags:
        event: MVPDagen2018

  - name: Create VM Extension
    azure_rm_virtualmachine_extension:
      auth_source: auto
      profile: default
      name: WACCustomScript
      resource_group: "RG-WindowsAdminCenter"
      virtual_machine_name: "ls-wac1"
      publisher: Microsoft.Azure.Extensions
      virtual_machine_extension_type: CustomScript
      type_handler_version: 2.0
      settings: '{"fileUris": ["https://raw.githubusercontent.com/morgansimonsen/MVPDagen2018/master/wac/Install-WAC.ps1"],"commandToExecute": "Install-WAC.ps1"}'
      auto_upgrade_minor_version: true