
- name: Deploy Windows Admin Center
  hosts: localhost
  gather_facts: no
  connection: local

  - name: Create virtual machine
    azure_rm_virtualmachine:
      auth_source: auto
      profile: default
      resource_group: "RG-WindowsAdminCenter"
      name: "ls-wac1"
      admin_username: "localadmin"
      admin_password: "VeryStrongP@ssw0rd!"
      managed_disk_type: "Premium_LRS"
      os_type: Windows
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: '2016-Datacenter'
        version: 'latest'
      open_ports:
       - 3389
       - 5986
       - 6516
      virtual_network_resource_group: "LangskipNetwork"
      virtual_network_name: "vNet-Langskip-WE"
      subnet: "Servers-Static"
      public_ip_allocation_method: Dynamic
      tags:
        event: MVPDagen2018

  - name: Create VM Extension
    azure_rm_virtualmachine_extension:
      auth_source: auto
      profile: default
      name: WACCustomScript
      resource_group: "RG-WindowsAdminCenter"
      virtual_machine_name: "ls-wac1"
      publisher: Microsoft.Azure.Extensions
      virtual_machine_extension_type: CustomScript
      type_handler_version: 2.0
      settings: '{"commandToExecute": "hostname"}'
      auto_upgrade_minor_version: true